# Generated by Django 5.1.1 on 2024-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='campaign_images/'),
        ),
    ]
