# Generated by Django 5.1.1 on 2024-09-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donations',
            field=models.IntegerField(default=0),
        ),
    ]
