# Generated by Django 5.1.1 on 2024-09-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_campaign_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='donations',
        ),
    ]
