# Generated by Django 5.1.1 on 2024-09-27 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_remove_campaign_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_list', to='donation.campaign'),
        ),
    ]
