# Generated by Django 5.1.1 on 2024-09-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_campaign_donations_alter_donation_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='donations',
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.campaign'),
        ),
    ]
