# Generated by Django 5.1.1 on 2024-09-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_remove_campaign_donations_alter_donation_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_donations', to='donation.campaign'),
        ),
    ]
