# Generated by Django 5.1.1 on 2024-09-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_donation_is_anonymous_donation_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_subscribed',
        ),
    ]
